name: Publish to Packagist

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist
      - name: Publish to Packagist
        uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          args: --no-interaction
          auth: ${{ secrets.PACKAGIST_API_TOKEN }}